project_id = "wiypiofuyrayywciovoo"

[api]
port = 54321
schemas = ["public", "graphql_public"]   # لاحظ: بدون "storage"
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.sms]
enable_signup = false

[storage]
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true
